### PR TITLE
Remove node_modules directory

### PR DESCRIPTION
**Pull request by wantaekchoi**
Hello!

This PR aims to remove the node_modules directory and performs the following tasks:

- Removes the node_modules directory.

The reasons for performing this task are as follows:

- Reduces the repository's size, resulting in shorter clone and download times by eliminating unnecessary data.
- Maintains the cleanliness and readability of the repository by not keeping unnecessary files.
- Allows developers to manage packages separately using the local node_modules directory when installing dependencies.

Please note that since this task can have an impact on the repository, it should only be merged after performing all relevant tests and reviewing the effects of this task.

Thank you!

116550121_110036414140665_6945591351731841420_n

### CODE REVIEW

**Comment by wantaekchoi** [comment]
Hello!

This PR updates the .gitignore file to exclude the node_modules directory from the repository.

The updated .gitignore file looks as follows:
```
...
# Ignore node_modules directory
node_modules/
```

Thank you!

**Comment by birariro** [comment]
I like what you say, but I don't accept it

**Comment by wantaekchoi** [comment]
We're blasting off again!!!

20ipgo

**Comment by birariro** [comment]
@wantaekchoi 

My mistake
While it's true that it won't work without the node module
but that was the wrong workaround.

I think you can use the github workflow to generate a dist file to remove the mod module.

**Comment by birariro** [comment]
@wantaekchoi 
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-and-push-your-action-to-github

The documentation says to upload node_modules along with it
But it also tells you how to remove node_modules using ncc

**Comment by wantaekchoi** [comment]
@birariro amazing!

**Pull request closed without merging**
